#!/bin/sh

uci -q batch << EOI
set network.lan.ipaddr='192.168.100.1'
delete network.wan6
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete network.globals.ula_prefix
set dhcp.@dnsmasq[0].filter_aaaa='1'
set network.lan.ifname='eth1 eth2 eth3'
set network.wan.ifname='eth0'
set system.led_wan.dev='eth0'
set fstab.@global[0].anon_mount='0'
set fstab.@global[0].auto_swap='0'
set fstab.@global[0].auto_mount='0'
set openclash.config.enable_meta_core='1'
set vsftpd.local.root='/'
set vsftpd.global.dotfile='1'
set vsftpd.global.lsrecurse='1'
set samba.@samba[0].autoshare='0'
set cpufreq.cpufreq.governor0='powersave'
set hd-idle.@hd-idle[0]=hd-idle
set hd-idle.@hd-idle[0].idle_time_unit='minutes'
set hd-idle.@hd-idle[0].idle_time_interval='3'
set hd-idle.@hd-idle[0].disk='sda'
set hd-idle.@hd-idle[0].enabled='0'
EOI

sed -i 's/US/CN/' /lib/wifi/mac80211.sh
sed -i 's/${mode_band}/2g/' /lib/wifi/mac80211.sh
sed -i 's/none/psk-mixed\n\t\t\tset wireless.default_radio${devidx}.key=scorpiofifth/' /lib/wifi/mac80211.sh

# device=`mount | grep "/rom" | awk '{print $1}'`
# device=${device:0:12}
# firstsector=$(( `echo -e "p\nq\n" | fdisk $device | grep 'p2' | awk '{print $3}'` + 1 ))
# echo -e "n\np\n3\n$firstsector\n\nw\n" | fdisk $device
# echo "y" | mkfs.ext4 ${device}p3
