#!/bin/ash

uci -q batch << EOI
set network.lan.ipaddr='192.168.100.1'
delete network.wan6
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
set dhcp.@dnsmasq[0].filter_aaaa='1'
set network.lan.ifname='eth1 eth2 eth3'
set network.wan.ifname='eth0'
set system.led_wan.dev='eth0'
set fstab.@global[0].anon_mount='0'
set fstab.@global[0].auto_swap='0'
set fstab.@global[0].auto_mount='0'
set openclash.config.enable_meta_core='1'
set vsftpd.local.root='/'
set vsftpd.global.dotfile='1'
set vsftpd.global.lsrecurse='1'
set samba.@samba[0].autoshare='0'
EOI

# delete dhcp.lan.ra_management
# delete dhcp.@dnsmasq[0].boguspriv
# delete dhcp.@dnsmasq[0].filterwin2k
# delete dhcp.@dnsmasq[0].nonegcache
# set wireless.radio0.country='CN'
# set wireless.radio0.channel='auto'
# set wireless.radio0.band='2g'
# set wireless.default_radio0.encryption='psk-mixed'
set wireless.default_radio0.key='scorpiofifth'
