name: Build(Default)
on: workflow_dispatch
jobs:
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: Preparation
        run: | 
          sudo apt install $(cat dependency) -y
          git clone -b master https://github.com/coolsnowwolf/lede.git build
      - name: Compile
        run: | 
          mkdir output
          cd build
          ./scripts/feeds update -a 
          ./scripts/feeds install -a
          wget https://raw.githubusercontent.com/scorpiofifth/OpenWrt/master/.config.origin -O .config
          make defconfig
          make download -j$(nproc)
          make -j$(nproc)
          rm -rf ./bin/targets/*/*/packages
          cp bin/targets/*/*/* ../output
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt
          path: output


