name: Compile(Tiny)
on: workflow_dispatch
jobs:
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: | 
          df -h
          sudo apt update
          sudo apt install $(cat other/dependencies) -y
          git clone https://github.com/coolsnowwolf/lede.git openwrt
          mkdir output
          cp config/diffconfig-tiny output/diffconfig-ori
      - name: Run scripts
        run: | 
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Colect config file
        run: | 
          cd openwrt
          cp ../config/diffconfig-tiny .config
          make defconfig
          ./scripts/diffconfig.sh | tee ../output/diffconfig-last
          cp .config ../output/config-last
      - name: Upload config file
        uses: actions/upload-artifact@v4
        with:
          name: config-tiny
          path: output
      - name: Compile
        run: | 
          cd openwrt
          make download -j$(nproc)
          make -j$(nproc)
          rm -rf ./bin/targets/*/*/packages
          cp bin/targets/*/*/* ../output
          df -h
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-tiny
          path: output
