name: Compile
on:
  workflow_dispatch:
  push:
    paths:
      - .config
      - .github/workflows/compile.yml
      - scripts/*
      - files/**
jobs:
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          temp-reserve-mb: 1
          swap-size-mb: 1
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: | 
          sudo apt update
          sudo apt install $(cat dependencies) -y
          git clone https://github.com/coolsnowwolf/lede.git openwrt
          cp -r files openwrt
          mkdir output
          cp .config output/config_before
      - name: Deal with feeds
        run: |
          cd openwrt
          ../scripts/first.sh
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ../.config .config
          ../scripts/second.sh
      - name: Colect config file
        run: | 
          cd openwrt
          make defconfig
          ./scripts/diffconfig.sh > ../output/diffconfig
          cp .config ../output/config_after
      - name: Upload config file
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: output
      - name: Compile
        run: | 
          cd openwrt
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s
          rm -rf ./bin/targets/*/*/packages
          cp bin/targets/*/*/* ../output
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output


